services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=text_messages
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - twotier
    healthcheck:
      test: ["CMD","mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  flask:
    build:
      context: .
    container_name: flaskapp
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=text_messages

    networks:
      - twotier
    ports:
      - "5000:5000"

    depends_on:
      - mysql

    restart: always

volumes:
  mysql-data:

networks:
  twotier : 
